export const initUserStatus = [
  { key: 1, value: "재직", label: "재직", index: 1 },
  { key: 2, value: "파견", label: "파견", index: 2 },
  { key: 3, value: "휴직", label: "휴직", index: 3 },
  { key: 4, value: "퇴사", label: "퇴사", index: 4 },
];
export const initUserContract = [
  { key: 1, value: "정직원", label: "정직원", index: 1 },
  { key: 2, value: "계약직", label: "계약직", index: 2 },
  { key: 3, value: "임시직", label: "임시직", index: 3 },
  { key: 4, value: "프리랜서", label: "프리랜서", index: 4 },
  { key: 5, value: "외부직원", label: "외부직원", index: 5 },
];
export const initUserSpot = [
  { key: 1, value: "회장", label: "회장", index: 1 },
  { key: 2, value: "부회장", label: "부회장", index: 2 },
  { key: 3, value: "사장", label: "사장", index: 3 },
  { key: 4, value: "부사장", label: "부사장", index: 4 },
  { key: 5, value: "전무", label: "전무", index: 5 },
  { key: 6, value: "상무", label: "상무", index: 6 },
  { key: 7, value: "이사", label: "이사", index: 7 },
  { key: 8, value: "부장", label: "부장", index: 8 },
  { key: 9, value: "차장", label: "차장", index: 9 },
  { key: 10, value: "과장", label: "과장", index: 10 },
  { key: 11, value: "대리", label: "대리", index: 11 },
  { key: 12, value: "사원", label: "사원", index: 12 },
  { key: 13, value: "인턴", label: "인턴", index: 13 },
];
export const initUserRank = [
  { key: 1, value: "실장", label: "실장", index: 1 },
  { key: 2, value: "팀장", label: "팀장", index: 2 },
  { key: 3, value: "팀원", label: "팀원", index: 3 },
];
export const initUserDepartment = [
  { key: 1, value: "인사부", label: "인사부", index: 1 },
  { key: 2, value: "영업부", label: "영업부", index: 2 },
  { key: 3, value: "마케팅부", label: "마케팅부", index: 3 },
  { key: 4, value: "재무부", label: "재무부", index: 4 },
  { key: 5, value: "회계부", label: "회계부", index: 5 },
  { key: 6, value: "연구개발부", label: "연구개발부", index: 6 },
  { key: 7, value: "생산부", label: "생산부", index: 7 },
  { key: 8, value: "구매부", label: "구매부", index: 8 },
  { key: 9, value: "고객지원부", label: "고개지원부", index: 9 },
  { key: 10, value: "법무부", label: "법무부", index: 10 },
];
export const initCategory = [
  {
    key: 1,
    name: "전산장비",
    depreciationType: "설정안함",
    depreciationPeriod: 0,
    index: 1,
    productLine: [
      {
        key: "1-1",
        name: "데스크탑",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 1,
      },
      {
        key: "1-2",
        name: "노트북",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 2,
      },
      {
        key: "1-3",
        name: "모니터",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 3,
      },
      {
        key: "1-4",
        name: "프린터",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 4,
      },
      {
        key: "1-5",
        name: "태블릿",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 5,
      },
      {
        key: "1-6",
        name: "TV",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 6,
      },
      {
        key: "1-7",
        name: "냉장고",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 7,
      },
      {
        key: "1-8",
        name: "스타일러",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 8,
      },
      {
        key: "1-9",
        name: "커피머신",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 9,
      },
      {
        key: "1-10",
        name: "세탁기",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 10,
      },
      {
        key: "1-11",
        name: "건조기",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 11,
      },
      {
        key: "1-12",
        name: "안마의자",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 12,
      },
    ],
  },
  {
    key: 2,
    name: "소프트웨어",
    depreciationType: "설정안함",
    depreciationPeriod: 0,
    index: 1,
    productLine: [
      {
        key: "2-1",
        name: "라이선스",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 1,
      },
      {
        key: "2-2",
        name: "구독형",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 2,
      },
    ],
  },
  {
    key: 3,
    name: "가구",
    depreciationType: "설정안함",
    depreciationPeriod: 0,
    index: 1,
    productLine: [
      {
        key: "3-1",
        name: "사무용책상",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 1,
      },
      {
        key: "3-2",
        name: "사무용의자",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 2,
      },
      {
        key: "3-3",
        name: "회의용테이블",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 3,
      },
      {
        key: "3-4",
        name: "회의용의자",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 4,
      },
      {
        key: "3-5",
        name: "싱크대",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 5,
      },
      {
        key: "3-6",
        name: "서랍장",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 6,
      },
    ],
  },
  {
    key: 4,
    name: "차량",
    depreciationType: "설정안함",
    depreciationPeriod: 0,
    index: 4,
    productLine: [
      {
        key: "4-1",
        name: "승용",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 1,
      },
      {
        key: "4-2",
        name: "승합",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 2,
      },
      {
        key: "4-3",
        name: "화물",
        depreciationType: "설정안함",
        depreciationPeriod: 0,
        index: 3,
      },
    ],
  },
  {
    key: 5,
    name: "기타",
    depreciationType: "설정안함",
    depreciationPeriod: 0,
    index: 5,
    productLine: [],
  },
];

export const initDescription = [
  {
    key: 1,
    productLine: "데스크탑",
    descritpionItem: [
      { key: 1, keyName: "프로세서", valueType: "autoComplete", isCount: true },
      { key: 3, keyName: "메모리", valueType: "autoComplete", isCount: true },
      { key: 5, keyName: "스토리지", valueType: "autoComplete", isCount: true },
      { key: 7, keyName: "칩셋", valueType: "autoComplete", isCount: false },
      {
        key: 9,
        keyName: "운영체제",
        valueType: "autoComplete",
        isCount: false,
      },
      {
        key: 11,
        keyName: "크기(W×D×H)",
        valueType: "textSize",
        isCount: false,
      },
      { key: 13, keyName: "비고", valueType: "textArea", isCount: false },
    ],
  },
  {
    key: 3,
    productLine: "노트북",
    descritpionItem: [
      {
        key: 1,
        keyName: "프로세서",
        valueType: "autoComplete",
        isCount: true,
      },
      { key: 3, keyName: "메모리", valueType: "autoComplete", isCount: true },
      {
        key: 5,
        keyName: "스토리지",
        valueType: "autoComplete",
        isCount: true,
      },
      {
        key: 7,
        keyName: "디스플레이",
        valueType: "autoComplete",
        isCount: false,
      },
      { key: 9, keyName: "해상도", valueType: "autoComplete", isCount: false },
      {
        key: 11,
        keyName: "운영체제",
        valueType: "autoComplete",
        isCount: false,
      },
      {
        key: 13,
        keyName: "크기(W×D×H)",
        valueType: "textSize",
        isCount: false,
      },
      { key: 15, keyName: "비고", valueType: "textArea", isCount: false },
    ],
  },
  {
    key: 5,
    productLine: "모니터",
    descritpionItem: [
      {
        key: 1,
        keyName: "디스플레이",
        valueType: "autoComplete",
        isCount: false,
      },
      { key: 3, keyName: "해상도", valueType: "autoComplete", isCount: false },
      { key: 5, keyName: "크기(W×D×H)", valueType: "textSize", isCount: false },
      { key: 7, keyName: "비고", valueType: "textArea", isCount: false },
    ],
  },

  {
    key: 9,
    productLine: "프린터",
    descritpionItem: [
      {
        key: 1,
        keyName: "인쇄방식",
        valueType: "autoComplete",
        isCount: false,
      },
      { key: 3, keyName: "메모리", valueType: "autoComplete", isCount: false },
      { key: 5, keyName: "해상도", valueType: "autoComplete", isCount: false },
      { key: 7, keyName: "크기(W×D×H)", valueType: "textSize", isCount: false },
      { key: 9, keyName: "비고", valueType: "textArea", isCount: false },
    ],
  },
  {
    key: 11,
    productLine: "태블릿",
    descritpionItem: [
      {
        key: 1,
        keyName: "프로세서",
        valueType: "autoComplete",
        isCount: false,
      },
      { key: 3, keyName: "메모리", valueType: "autoComplete", isCount: false },
      {
        key: 5,
        keyName: "디스플레이",
        valueType: "autoComplete",
        isCount: false,
      },
      { key: 7, keyName: "해상도", valueType: "autoComplete", isCount: false },
      {
        key: 9,
        keyName: "운영체제",
        valueType: "autoComplete",
        isCount: false,
      },
      {
        key: 11,
        keyName: "크기(W×D×H)",
        valueType: "textSize",
        isCount: false,
      },
      { key: 13, keyName: "비고", valueType: "textArea", isCount: false },
    ],
  },
  {
    key: 13,
    productLine: "TV",
    descritpionItem: [
      {
        key: 1,
        keyName: "디스플레이",
        valueType: "autoComplete",
        isCount: false,
      },
      { key: 3, keyName: "해상도", valueType: "autoComplete", isCount: false },
      { key: 5, keyName: "크기(W×D×H)", valueType: "textSize", isCount: false },
      { key: 7, keyName: "비고", valueType: "textArea", isCount: false },
    ],
  },
];

export const initDepreciationType = [
  { key: "정액법", value: "정액법" },
  { key: "정률법", value: "정률법" },
  { key: "설정안함", value: "설정안함" },
];

export const initDepreciationPeriod = [
  { key: "5년", value: 5, label: "5년" },
  {
    key: "10년",
    value: 10,
    label: "10년",
  },
  { key: "6년", value: 6, label: "6년" },
  { key: "7년", value: 7, label: "7년" },
  { key: "8년", value: 8, label: "8년" },
  { key: "9년", value: 9, label: "9년" },
  {
    key: "설정안함",
    value: 0,
    label: "설정안함",
  },
];
export const initDepreciationRate = [
  { key: "50%", value: 50, label: "50%" },
  { key: "10%", value: 10, label: "10%" },
  { key: "20%", value: 20, label: "20%" },
  { key: "30%", value: 30, label: "30%" },
  { key: "40%", value: 40, label: "40%" },
  {
    key: "설정안함",
    value: 0,
    label: "설정안함",
  },
];

export const assetInfoFieldName = [
  {
    keyName: "id",
    label: "일련번호",
    index: 0,
    hidden: true,
    type: "시스템",
  },
  {
    keyName: "firstPics",
    label: "최초사진",
    index: 1,
    hidden: true,
    type: "타이틀",
    span: 8,
  },
  {
    keyName: "assetName",
    label: "자산명",
    index: 11,
    hidden: true,
    type: "자산",
    span: 4,
  },
  {
    keyName: "assetCode",
    label: "자산코드",
    index: 1,
    hidden: false,
    type: "타이틀",
    span: 4,
  },

  {
    keyName: "assetPurchasedType",
    label: "취득방식",
    index: 2,
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetVendor",
    label: "제조사",
    index: 3,
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetCategory",
    label: "분류",
    index: 4,
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetProductLine",
    label: "품목",
    index: 5,
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetModel",
    label: "모델명",
    index: 7,
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetOwnerCompany",
    label: "자산소유사",
    index: 9,
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetPurchasedDate",
    label: "구입일자",
    index: 11,
    hidden: false,
    type: "거래",
    span: 1,
  },
  {
    keyName: "assetPurchasedDateConverted",
    label: "구입일자",
    index: 11,
    hidden: false,
    type: "거래",
    span: 1,
  },
  {
    keyName: "assetWarranty",
    label: "보증기간",
    index: 13,
    hidden: false,
    type: "자산",
    span: 1,
    afterAddon: "개월",
  },

  {
    keyName: "assetRentalPeriod",
    label: "렌탈기간",
    index: 15,
    hidden: false,
    type: "자산",
    span: 1,
  },

  {
    keyName: "assetPurchaseName",
    label: "구매처",
    index: 15,
    hidden: false,
    type: "거래",
    span: 1,
  },
  {
    keyName: "createdAt",
    label: "등록일자",
    index: 19,
    hidden: false,
    type: "거래",
    span: 1,
  },
  {
    keyName: "createdAtConverted",
    label: "등록일자",
    index: 19,
    hidden: false,
    type: "거래",
    span: 1,
  },
  {
    keyName: "assetCost",
    label: "취득원가",
    index: 21,
    valueType: "number",
    hidden: false,
    type: "거래",
    span: 1,
    afterAddon: "원",
  },
  {
    keyName: "assetDepreciationType",
    label: "감가방식",
    index: 17,
    hidden: true,
    type: "거래",
    span: 1,
  },
  {
    keyName: "assetDepreciationPeroid",
    label: "감가기간(율)",
    index: 19,
    hidden: true,
    type: "거래",
    span: 1,
  },
  {
    keyName: "userInfo",
    label: "사용자",
    index: 29,
    hidden: false,
    type: "사용자",
    span: 1,
  },
  {
    keyName: "location",
    label: "현재위치",
    index: 31,
    hidden: false,
    type: "사용자",
    span: 1,
  },
  {
    keyName: "assetOwner",
    label: "등록ID",
    index: 33,
    hidden: true,
    type: "시스템",
  },
  {
    keyName: "assetDescritionSummay",
    label: "스펙",
    index: 35,
    hidden: true,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetAccessory",
    label: "구성품",
    index: 37,
    valueType: "array",
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetAssignDateConverted",
    label: "배정일자",
    index: 39,
    valueType: "date",
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "isReturnDate",
    label: "반환설정",
    index: 41,
    valueType: "boolean",
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetReturnDateConverted",
    label: "반환일자",
    index: 43,
    valueType: "date",
    hidden: false,
    type: "자산",
    span: 1,
  },
  {
    keyName: "assetMemo",
    label: "비고",
    index: 2000,
    valueType: "context",
    hidden: false,
    type: "자산",
    span: 4,
  },
  {
    keyName: "assetUID",
    label: "자산시스템코드",
    index: 41,
    valueType: "text",
    hidden: true,
    type: "자산",
    span: 1,
  },
];
